#Dockerfile for MEAN stack
#docker version 1.2.0, build fa7b24f
FROM docker.brighterlink.io:443/bldev/cloudbase:latest
MAINTAINER Samar Acharya <samar@techgaun.com>

ENV SRV_DIR /var/app
#install NPM modules
#ADD package.json /tmp/package.json
#RUN cd /tmp && npm install

COPY ./.docker/supervisord.nodejs.cloud.conf /etc/supervisord.d/supervisord.nodejs.conf

WORKDIR /var/app

USER nobody
EXPOSE 3000
USER root
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
