'use strict';

angular.module('bl.analyze.solar.surface')
    .constant('tznames', {
      'ACDT': 'Australian Central Daylight Savings Time',
      'ACST': 'Australian Central Standard Time',
      'ACT': {'300': 'Acre Time', '-480': 'ASEAN Common Time'},
      'ADT': 'Atlantic Daylight Time',
      'AEDT': 'Australian Eastern Daylight Savings Time',
      'AEST': 'Australian Eastern Standard Time',
      'AFT': 'Afghanistan Time',
      'AKDT': 'Alaska Daylight Time',
      'AKST': 'Alaska Standard Time',
      'ALMT': 'Alma-Ata Time',
      'AMST': {'180': 'Amazon Summer Time', '-300': 'Armenia Summer Time'},
      'AMT': {'240': 'Amazon Time', '-240': 'Armenia Time'},
      'ART': 'Argentina Time',
      'AST': {'-180': 'Arabia Standard Time', '240': 'Atlantic Standard Time'},
      'AWDT': 'Australian Western Daylight Time',
      'AWST': 'Australian Western Standard Time',
      'AZOST': 'Azores Standard Time',
      'AZT': 'Azerbaijan Time',
      'BDT': {'-480': 'Brunei Time', '-360': 'Bangladesh Daylight Time'},
      'BIOT': 'British Indian Ocean Time',
      'BIT': 'Baker Island Time',
      'BOT': 'Bolivia Time',
      'BRST': 'Brasilia Summer Time',
      'BRT': 'Brasilia Time',
      'BST': {'-360':'Bangladesh Standard Time','-660':'Bougainville Standard Time','-60':'British Summer Time'},
      'BTT': 'Bhutan Time',
      'CAT': 'Central Africa Time',
      'CCT': 'Cocos Islands Time',
      'CDT': {'300':'Central Daylight Time','240':'Cuba Daylight Time'},
      'CEDT': 'Central European Daylight Time',
      'CEST': 'Central European Summer Time',
      'CET': 'Central European Time',
      'CHADT': 'Chatham Daylight Time',
      'CHAST': 'Chatham Standard Time',
      'CHOT': 'Choibalsan',
      'ChST': 'Chamorro Standard Time',
      'CHUT': 'Chuuk Time',
      'CIST': 'Clipperton Island Standard Time',
      'CIT': 'Central Indonesia Time',
      'CKT': 'Cook Island Time',
      'CLST': 'Chile Summer Time',
      'CLT': 'Chile Standard Time',
      'COST': 'Colombia Summer Time',
      'COT': 'Colombia Time',
      'CST': {'360':'Central Standard Time','-480':'China Standard Time',
        '-570':'Central Standard Time','-630':'Central Summer Time','300':'Cuba Standard Time'},
      'CT': 'China time',
      'CVT': 'Cape Verde Time',
      'CWST': 'Central Western Standard Time',
      'CXT': 'Christmas Island Time',
      'DAVT': 'Davis Time',
      'DDUT': 'Dumont d\'Urville Time',
      'DFT': 'AIX specific equivalent of Central European Time',
      'EASST': 'Easter Island Standard Summer Time',
      'EAST': 'Easter Island Standard Time',
      'EAT': 'East Africa Time',
      'ECT': {'240':'Eastern Caribbean Time','300':'Ecuador Time'},
      'EDT': 'Eastern Daylight Time',
      'EEDT': 'Eastern European Daylight Time',
      'EEST': 'Eastern European Summer Time',
      'EET': 'Eastern European Time',
      'EGST': 'Eastern Greenland Summer Time',
      'EGT': 'Eastern Greenland Time',
      'EIT': 'Eastern Indonesian Time',
      'EST': 'Eastern Standard Time',
      //'EST': 'Eastern Standard Time',
      'FET': 'Further-eastern European Time',
      'FJT': 'Fiji Time',
      'FKST': 'Falkland Islands Standard Time',
      //'FKST': 'Falkland Islands Summer Time',
      'FKT': 'Falkland Islands Time',
      'FNT': 'Fernando de Noronha Time',
      'GALT': 'Galapagos Time',
      'GAMT': 'Gambier Islands',
      'GET': 'Georgia Standard Time',
      'GFT': 'French Guiana Time',
      'GILT': 'Gilbert Island Time',
      'GIT': 'Gambier Island Time',
      'GMT': 'Greenwich Mean Time',
      'GST': {'120':'South Georgia and the South Sandwich Islands','-240':'Gulf Standard Time'},
      'GYT': 'Guyana Time',
      'HADT': 'Hawaii-Aleutian Daylight Time',
      'HAEC': 'Heure Avancee d\'Europe Centrale francised name for CEST',
      'HAST': 'Hawaii-Aleutian Standard Time',
      'HKT': 'Hong Kong Time',
      'HMT': 'Heard and McDonald Islands Time',
      'HOVT': 'Khovd Time',
      'HST': 'Hawaii Standard Time',
      'IBST': 'International Business Standard Time',
      'ICT': 'Indochina Time',
      'IDT': 'Israel Daylight Time',
      'IOT': 'Indian Ocean Time',
      'IRDT': 'Iran Daylight Time',
      'IRKT': 'Irkutsk Time',
      'IRST': 'Iran Standard Time',
      'IST': {'-330':'Indian Standard Time','-60':'Irish Standard Time','-120':'Israel Standard Time'},
      'JST': 'Japan Standard Time',
      'KGT': 'Kyrgyzstan time',
      'KOST': 'Kosrae Time',
      'KRAT': 'Krasnoyarsk Time',
      'KST': 'Korea Standard Time',
      'LHST': {'-630':'Lord Howe Standard Time','-660':'Lord Howe Summer Time'},
      'LINT': 'Line Islands Time',
      'MAGT': 'Magadan Time',
      'MART': 'Marquesas Islands Time',
      'MAWT': 'Mawson Station Time',
      'MDT': 'Mountain Daylight Time',
      'MET': 'Middle European Time Same zone as CET',
      'MEST': 'Middle European Summer Time Same zone as CEST',
      'MHT': 'Marshall Islands',
      'MIST': 'Macquarie Island Station Time',
      'MIT': 'Marquesas Islands Time',
      'MMT': 'Myanmar Time',
      'MSK': 'Moscow Time',
      'MST': {'-480':'Malaysia Standard Time','420':'Mountain Standard Time','-390':'Myanmar Standard Time'},
      'MUT': 'Mauritius Time',
      'MVT': 'Maldives Time',
      'MYT': 'Malaysia Time',
      'NCT': 'New Caledonia Time',
      'NDT': 'Newfoundland Daylight Time',
      'NFT': 'Norfolk Time',
      'NPT': 'Nepal Time',
      'NST': 'Newfoundland Standard Time',
      'NT': 'Newfoundland Time',
      'NUT': 'Niue Time',
      'NZDT': 'New Zealand Daylight Time',
      'NZST': 'New Zealand Standard Time',
      'OMST': 'Omsk Time',
      'ORAT': 'Oral Time',
      'PDT': 'Pacific Daylight Time',
      'PET': 'Peru Time',
      'PETT': 'Kamchatka Time',
      'PGT': 'Papua New Guinea Time',
      'PHOT': 'Phoenix Island Time',
      'PKT': 'Pakistan Standard Time',
      'PMDT': 'Saint Pierre and Miquelon Daylight time',
      'PMST': 'Saint Pierre and Miquelon Standard Time',
      'PONT': 'Pohnpei Standard Time',
      'PST': {'480':'Pacific Standard Time','-480':'Philippine Standard Time'},
      'PYST': 'Paraguay Summer Time',
      'PYT': 'Paraguay Time',
      'RET': 'Reunion Time',
      'ROTT': 'Rothera Research Station Time',
      'SAKT': 'Sakhalin Island time',
      'SAMT': 'Samara Time',
      'SAST': 'South African Standard Time',
      'SBT': 'Solomon Islands Time',
      'SCT': 'Seychelles Time',
      'SGT': 'Singapore Time',
      'SLST': 'Sri Lanka Standard Time',
      'SRET': 'Srednekolymsk Time',
      'SRT': 'Suriname Time',
      'SST': {'660':'Samoa Standard Time','-480':'Singapore Standard Time'},
      'SYOT': 'Showa Station Time',
      'TAHT': 'Tahiti Time',
      'THA': 'Thailand Standard Time',
      'TFT': 'Indian/Kerguelen',
      'TJT': 'Tajikistan Time',
      'TKT': 'Tokelau Time',
      'TLT': 'Timor Leste Time',
      'TMT': 'Turkmenistan Time',
      'TOT': 'Tonga Time',
      'TVT': 'Tuvalu Time',
      'UCT': 'Coordinated Universal Time',
      'ULAT': 'Ulaanbaatar Time',
      'USZ1': 'Kaliningrad Time',
      'UTC': 'Coordinated Universal Time',
      'UYST': 'Uruguay Summer Time',
      'UYT': 'Uruguay Standard Time',
      'UZT': 'Uzbekistan Time',
      'VET': 'Venezuelan Standard Time',
      'VLAT': 'Vladivostok Time',
      'VOLT': 'Volgograd Time',
      'VOST': 'Vostok Station Time',
      'VUT': 'Vanuatu Time',
      'WAKT': 'Wake Island Time',
      'WAST': 'West Africa Summer Time',
      'WAT': 'West Africa Time',
      'WEDT': 'Western European Daylight Time',
      'WEST': 'Western European Summer Time',
      'WET': 'Western European Time',
      'WIT': 'Western Indonesian Time',
      'WST': 'Western Standard Time',
      'YAKT': 'Yakutsk Time',
      'YEKT': 'Yekaterinburg Time',
      'Z': 'Zulu Time'
    });

/*
        if (tz == 'ACDT') tz = '';
        else if (tz == '') tz = '';
        else if (tz == '' && offset == 300) tz = 'Acre Time'; //UTC?05
        else if (tz == 'ACT' && offset == -480) tz = 'ASEAN Common Time'; //UTC+08
        else if (tz == '') tz = 'Atlantic Daylight Time';
        else if (tz == '') tz = 'Australian Eastern Daylight Savings Time';
        else if (tz == '') tz = 'Australian Eastern Standard Time';
        else if (tz == '') tz = 'Afghanistan Time';
        else if (tz == '') tz = 'Alaska Daylight Time';
        else if (tz == '') tz = 'Alaska Standard Time';
        else if (tz == '' && offset == 180) tz = 'Amazon Summer Time';
        else if (tz == 'AMST' && offset == -300)  tz = 'Armenia Summer Time';
        else if (tz == 'AMT' && offset == 240) tz = 'Amazon Time';
        else if (tz == 'AMT' && offset == -240) tz = 'Armenia Time';
        else if (tz == 'ART') tz = 'Argentina Time';
        return tz;
      };
    }]);*/
